### ISSUE TITLE
Empty catalog view

### ISSUE THREAD

**Issue by xyntechx** [asuc-octo/berkeleytime#657] opened 2023-11-14 03:20 UTC
Currently, the catalog just displays an empty view when no class has been selected. Instead, figure out a way to do the following:
- [ ] Save recent searches to `localStorage` and display (this might take some extra consideration; I would suggest displaying the search and the semester but save all filters)
- [ ] Display saved classes
- [ ] Add an "X" button so the user can deselect any class they have selected and return to the empty view with recent searches, recent classes, etc.

**Comment by Jdyn** [comment] 2023-11-14 20:22
Hello what is the plan for this? Is this a duplicate of #624? I have work on this in progress already

**Comment by xyntechx** [comment] 2023-11-14 21:14
@Jdyn oh icic. Matt and I just synced about this yesterday so I didn't know you were already working on it. @mathhulk should Jayden handle this task then?

**Closed** 2023-11-28 03:35 UTC
